// <auto-generated />
using System;
using Fiap.Api.Donation1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Api.Donation1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231118111058_AddProdutos")]
    partial class AddProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.Donation1.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SugestaoTroca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.HasIndex("DataCadastro");

                    b.HasIndex("TipoProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            ProdutoId = 6,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1971),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1971),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 6",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 7,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1980),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1980),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 7",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 8,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1982),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1982),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 8",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 9,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1984),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1985),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 9",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 10,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1987),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1987),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 10",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 11,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1989),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1989),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 11",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 12,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1991),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1992),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 12",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 13,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1993),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1994),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 13",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 14,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1996),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1996),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 14",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 15,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1998),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(1998),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 15",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 16,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2000),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2000),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 16",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 17,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2002),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2002),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 17",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 18,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2004),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2004),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 18",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 19,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2006),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2007),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 19",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 20,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2008),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2009),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 20",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 21,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2010),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2011),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 21",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 22,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2012),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2013),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 22",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 23,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2015),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2015),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 23",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 24,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2017),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2017),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 24",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 25,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2019),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2019),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 25",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 26,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2021),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2022),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 26",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 27,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2023),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2024),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 27",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 28,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2025),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2026),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 28",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 29,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2027),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2028),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 29",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 30,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2083),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2083),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 30",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 31,
                            DataCadastro = new DateTime(2023, 11, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2085),
                            DataExpiracao = new DateTime(2025, 5, 18, 8, 10, 57, 816, DateTimeKind.Local).AddTicks(2085),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 31",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.TipoProdutoModel", b =>
                {
                    b.Property<int>("TipoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoProdutoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NomeTipoProduto")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("TipoProdutoId");

                    b.ToTable("TipoProduto");

                    b.HasData(
                        new
                        {
                            TipoProdutoId = 1,
                            Descricao = "Descriçao para celular",
                            NomeTipoProduto = "Celular"
                        },
                        new
                        {
                            TipoProdutoId = 2,
                            Descricao = "Descriçao para Tvs",
                            NomeTipoProduto = "Tvs"
                        },
                        new
                        {
                            TipoProdutoId = 3,
                            Descricao = "Descriçao para ar-condicionado",
                            NomeTipoProduto = "Ar-condicionado"
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Regra")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            EmailUsuario = "sa@fiap.com.br",
                            NomeUsuario = "Super Admin",
                            Regra = "admin",
                            Senha = "123456"
                        },
                        new
                        {
                            UsuarioId = 2,
                            EmailUsuario = "joao@fiap.com.br",
                            NomeUsuario = "Joao",
                            Regra = "admin",
                            Senha = "123456"
                        },
                        new
                        {
                            UsuarioId = 3,
                            EmailUsuario = "flavio@fiap.com.br",
                            NomeUsuario = "Flavio",
                            Regra = "admin",
                            Senha = "123456"
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.ProdutoModel", b =>
                {
                    b.HasOne("Fiap.Api.Donation1.Models.TipoProdutoModel", "TipoProduto")
                        .WithMany()
                        .HasForeignKey("TipoProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Api.Donation1.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProduto");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
